CREATE TABLE `languages` (
  `language_code` varchar(2) NOT NULL,
  `language` varchar(255) NOT NULL,
  PRIMARY KEY (`language_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `symbols` (
  `symbol_id` int NOT NULL AUTO_INCREMENT,
  `file_name` varchar(255) NOT NULL,
  `size` int DEFAULT NULL,
  `active` boolean DEFAULT 0,
  `deleted` boolean DEFAULT 0,
  PRIMARY KEY (`symbol_id`),
  UNIQUE (`file_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `keywords` (
  `keyword_id` int NOT NULL AUTO_INCREMENT,
  `keyword` varchar(255) NOT NULL,
  `language_code` varchar(2) NOT NULL,
  PRIMARY KEY (`keyword_id`),
  FOREIGN KEY (`language_code`) REFERENCES `languages`(`language_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `categories` (
  `category_id` int NOT NULL AUTO_INCREMENT,
  `category` varchar(255) NOT NULL,
--   a rajouter si l'ont souhaite optimiser l'ordre dans lequel les catégories apparaissent
--   `category_order` int DEFAULT NULL, 
  `language_code` varchar(2) NOT NULL,
  PRIMARY KEY (`category_id`),
  FOREIGN KEY (`language_code`) REFERENCES `languages`(`language_code`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `symbol_keyword` (
  `symbol_id` int NOT NULL,
  `keyword_id` int NOT NULL,
  PRIMARY KEY (`symbol_id`, `keyword_id`),
  FOREIGN KEY (`symbol_id`) REFERENCES `symbols`(`symbol_id`),
  FOREIGN KEY (`keyword_id`) REFERENCES `keywords`(`keyword_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `symbol_category` (
  `symbol_id` int NOT NULL,
  `category_id` int NOT NULL,
  PRIMARY KEY (`symbol_id`, `category_id`),
  FOREIGN KEY (`symbol_id`) REFERENCES `symbols`(`symbol_id`),
  FOREIGN KEY (`category_id`) REFERENCES `categories`(`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- insert des 6 langages
INSERT INTO `languages` (`language_code`, `language_name`) VALUES
('EN', 'Anglais'),
('DE', 'Allemand'),
('ES', 'Espagnol'),
('FR', 'Français'),
('IT', 'Italien'),
('PT', 'Portugais');

-- Insert de toutes les categories + leurs 6 traductions
INSERT INTO `categories` (`category`, `language_code`) VALUES
('Mécanique', 'FR'),
('Médical', 'FR'),
('Musique et Son', 'FR'),
('Nature', 'FR'),
('Noël', 'FR'),
('Nourriture et Boisson', 'FR'),
('Objet', 'FR'),
('Photo et Vidéo', 'FR'),
('Sécurité', 'FR'),
('Signe et Symbole', 'FR'),
('Sport', 'FR'),
('Symboles', 'FR'),
('Temps - Météo', 'FR'),
('Transport', 'FR'),
('Vacances', 'FR'),
('Animal', 'FR'),
('Anniversaire', 'FR'),
('Arme', 'FR'),
('Bâtiment et Pays', 'FR'),
('Boîte', 'FR'),
('Bulle de Parole', 'FR'),
('Carte et Localisation', 'FR'),
('Communication et Réseau', 'FR'),
('Doigt', 'FR'),
('École', 'FR'),
('Enfant', 'FR'),
('Entreprise et Finance', 'FR'),
('Espace', 'FR'),
('Événement', 'FR'),
('Fichier', 'FR'),
('Flèche', 'FR'),
('Format de Fichier', 'FR'),
('Vêtement et Accessoire', 'FR'),
('Humain', 'FR'),
('Illustrations pour Gobelets', 'FR'),
('Industrie', 'FR'),
('Informatique', 'FR'),
('Insectes', 'FR'),
('Maison', 'FR'),
('Mariage', 'FR'),

('Mechanical', 'EN'),
('Medical', 'EN'),
('Music and Sound', 'EN'),
('Nature', 'EN'),
('Christmas', 'EN'),
('Food and Drink', 'EN'),
('Object', 'EN'),
('Photo and Video', 'EN'),
('Security', 'EN'),
('Sign and Symbol', 'EN'),
('Sport', 'EN'),
('Symbols', 'EN'),
('Weather', 'EN'),
('Transportation', 'EN'),
('Vacation', 'EN'),
('Animal', 'EN'),
('Birthday', 'EN'),
('Weapon', 'EN'),
('Building and Country', 'EN'),
('Box', 'EN'),
('Speech Bubble', 'EN'),
('Map and Location', 'EN'),
('Communication and Network', 'EN'),
('Finger', 'EN'),
('School', 'EN'),
('Child', 'EN'),
('Business and Finance', 'EN'),
('Space', 'EN'),
('Event', 'EN'),
('File', 'EN'),
('Arrow', 'EN'),
('File Format', 'EN'),
('Clothing and Accessory', 'EN'),
('Human', 'EN'),
('Cup Illustrations', 'EN'),
('Industry', 'EN'),
('Computer', 'EN'),
('Insects', 'EN'),
('House', 'EN'),
('Wedding', 'EN'),

('Mechanik', 'DE'),
('Medizinisch', 'DE'),
('Musik und Ton', 'DE'),
('Natur', 'DE'),
('Weihnachten', 'DE'),
('Essen und Trinken', 'DE'),
('Objekt', 'DE'),
('Foto und Video', 'DE'),
('Sicherheit', 'DE'),
('Zeichen und Symbol', 'DE'),
('Sport', 'DE'),
('Symbole', 'DE'),
('Wetter', 'DE'),
('Transport', 'DE'),
('Urlaub', 'DE'),
('Tier', 'DE'),
('Geburtstag', 'DE'),
('Waffe', 'DE'),
('Gebäude und Land', 'DE'),
('Box', 'DE'),
('Sprechblase', 'DE'),
('Karte und Standort', 'DE'),
('Kommunikation und Netzwerk', 'DE'),
('Finger', 'DE'),
('Schule', 'DE'),
('Kind', 'DE'),
('Business und Finanzen', 'DE'),
('Weltraum', 'DE'),
('Veranstaltung', 'DE'),
('Datei', 'DE'),
('Pfeil', 'DE'),
('Dateiformat', 'DE'),
('Kleidung und Accessoire', 'DE'),
('Mensch', 'DE'),
('Becher-Illustrationen', 'DE'),
('Industrie', 'DE'),
('Computer', 'DE'),
('Insekten', 'DE'),
('Haus', 'DE'),
('Hochzeit', 'DE'),

('Mecánica', 'ES'),
('Médico', 'ES'),
('Música y Sonido', 'ES'),
('Naturaleza', 'ES'),
('Navidad', 'ES'),
('Comida y Bebida', 'ES'),
('Objeto', 'ES'),
('Foto y Video', 'ES'),
('Seguridad', 'ES'),
('Signo y Símbolo', 'ES'),
('Deporte', 'ES'),
('Símbolos', 'ES'),
('Tiempo', 'ES'),
('Transporte', 'ES'),
('Vacaciones', 'ES'),
('Animal', 'ES'),
('Cumpleaños', 'ES'),
('Arma', 'ES'),
('Edificio y País', 'ES'),
('Caja', 'ES'),
('Bocadillo de Diálogo', 'ES'),
('Mapa y Ubicación', 'ES'),
('Comunicación y Red', 'ES'),
('Dedo', 'ES'),
('Escuela', 'ES'),
('Niño', 'ES'),
('Negocios y Finanzas', 'ES'),
('Espacio', 'ES'),
('Evento', 'ES'),
('Archivo', 'ES'),
('Flecha', 'ES'),
('Formato de Archivo', 'ES'),
('Ropa y Accesorio', 'ES'),
('Humano', 'ES'),
('Ilustraciones para Vasos', 'ES'),
('Industria', 'ES'),
('Informática', 'ES'),
('Insectos', 'ES'),
('Casa', 'ES'),
('Boda', 'ES'),

('Meccanica', 'IT'),
('Medico', 'IT'),
('Musica e Suono', 'IT'),
('Natura', 'IT'),
('Natale', 'IT'),
('Cibo e Bevande', 'IT'),
('Oggetto', 'IT'),
('Foto e Video', 'IT'),
('Sicurezza', 'IT'),
('Segno e Simbolo', 'IT'),
('Sport', 'IT'),
('Simboli', 'IT'),
('Meteo', 'IT'),
('Trasporti', 'IT'),
('Vacanze', 'IT'),
('Animale', 'IT'),
('Compleanno', 'IT'),
('Arma', 'IT'),
('Edificio e Paese', 'IT'),
('Scatola', 'IT'),
('Fumetto', 'IT'),
('Mappa e Posizione', 'IT'),
('Comunicazione e Rete', 'IT'),
('Dito', 'IT'),
('Scuola', 'IT'),
('Bambino', 'IT'),
('Affari e Finanza', 'IT'),
('Spazio', 'IT'),
('Evento', 'IT'),
('File', 'IT'),
('Freccia', 'IT'),
('Formato di File', 'IT'),
('Abbigliamento e Accessorio', 'IT'),
('Umano', 'IT'),
('Illustrazioni per Bicchieri', 'IT'),
('Industria', 'IT'),
('Informatica', 'IT'),
('Insetti', 'IT'),
('Casa', 'IT'),
('Matrimonio', 'IT'),

('Mecânica', 'PT'),
('Médico', 'PT'),
('Música e Som', 'PT'),
('Natureza', 'PT'),
('Natal', 'PT'),
('Comida e Bebida', 'PT'),
('Objeto', 'PT'),
('Foto e Vídeo', 'PT'),
('Segurança', 'PT'),
('Sinal e Símbolo', 'PT'),
('Desporto', 'PT'),
('Símbolos', 'PT'),
('Tempo - Clima', 'PT'),
('Transporte', 'PT'),
('Férias', 'PT'),
('Animal', 'PT'),
('Aniversário', 'PT'),
('Arma', 'PT'),
('Edifício e País', 'PT'),
('Caixa', 'PT'),
('Balão de Fala', 'PT'),
('Mapa e Localização', 'PT'),
('Comunicação e Rede', 'PT'),
('Dedo', 'PT'),
('Escola', 'PT'),
('Criança', 'PT'),
('Negócio e Finanças', 'PT'),
('Espaço', 'PT'),
('Evento', 'PT'),
('Arquivo', 'PT'),
('Seta', 'PT'),
('Formato de Arquivo', 'PT'),
('Vestuário e Acessório', 'PT'),
('Humano', 'PT'),
('Ilustrações para Copos', 'PT'),
('Indústria', 'PT'),
('Informática', 'PT'),
('Insetos', 'PT'),
('Casa', 'PT'),
('Casamento', 'PT');